# Generated by ChatGPT

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_coresettings_block_local_user_logon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coresettings",
            name="ticket_priority_options",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=50),
                default=list,
                blank=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="coresettings",
            name="ticket_status_options",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=50),
                default=list,
                blank=True,
                size=None,
            ),
        ),
    ]

